### ISSUE TITLE
Errors in image of Figure 4 in Chapter 7 (Machine translation)

### ISSUE THREAD

**Issue by Haichao-Zhang** [PaddlePaddle/book#112]
(1) For this image:

https://github.com/PaddlePaddle/book/blob/develop/machine_translation/image/encoder_decoder.png

the locations of "源语言编码状态" and “源语言词序列” should be switched.

(2) For this image

https://github.com/PaddlePaddle/book/blob/develop/machine_translation/image/encoder_decoder_en.png

similarly, the locations of "Word Embedding Sequence for the Source Language" and “Word Sequence for the Source Sequence” should be switched.

**Comment by llxxxll** [comment]
This is the same issue as #110

**Comment by wangkuiyi** [comment]
This duplicates with #110
