### ISSUE TITLE
Translate figures in Chapter 8

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/book#115]
We need the translation of Figure 3. only, as Figure 1. and 2. came from the Google Youtube paper.

**Comment by llxxxll** [comment]
求中英对照。

**Comment by wangkuiyi** [comment]
The image 

https://github.com/PaddlePaddle/book/blob/develop/recommender_system/image/rec_regression_network.png

余弦相似度 => cosine similarity
用户特征 => user features
电影特征 => movie features

ID特征 => ID feature
性别特征 => gender feature
职业特征 => occupation feature
年龄特征 => age feature
ID => ID
性别 => gender
职业 => occupation
年龄 => age
用户 => user

类型特征 => genres feature
定长电影名特征 => fixed-length feature vector
降采样 => down-sampling
电影名时序特征 => time-series feature
卷积层+全连接 => convolution and fully-connected layers
电影名 => name/title
电影 => movie
