### ISSUE TITLE
image_classification killed

### ISSUE THREAD

**Issue by sunnysuhappy** [PaddlePaddle/book#144]
我用docker安装的，使用了cpu版本，进行vgg或者resNet训练时候报错
I0307 09:38:06.377203   355 Util.cpp:130] Calling runInitFunctions
I0307 09:38:06.377521   355 Util.cpp:143] Call runInitFunctions done.
[INFO 2017-03-07 09:38:06,464 layers.py:1890] channels=3 size=3072
[INFO 2017-03-07 09:38:06,464 layers.py:1890] output size for __conv_0__ is 32
[INFO 2017-03-07 09:38:06,466 layers.py:1890] channels=64 size=65536
[INFO 2017-03-07 09:38:06,466 layers.py:1890] output size for __conv_1__ is 32
[INFO 2017-03-07 09:38:06,468 layers.py:1985] output size for __pool_0__ is 16*16
[INFO 2017-03-07 09:38:06,469 layers.py:1890] channels=64 size=16384
[INFO 2017-03-07 09:38:06,469 layers.py:1890] output size for __conv_2__ is 16
[INFO 2017-03-07 09:38:06,471 layers.py:1890] channels=128 size=32768
[INFO 2017-03-07 09:38:06,471 layers.py:1890] output size for __conv_3__ is 16
[INFO 2017-03-07 09:38:06,472 layers.py:1985] output size for __pool_1__ is 8*8
[INFO 2017-03-07 09:38:06,473 layers.py:1890] channels=128 size=8192
[INFO 2017-03-07 09:38:06,473 layers.py:1890] output size for __conv_4__ is 8
[INFO 2017-03-07 09:38:06,475 layers.py:1890] channels=256 size=16384
[INFO 2017-03-07 09:38:06,475 layers.py:1890] output size for __conv_5__ is 8
[INFO 2017-03-07 09:38:06,477 layers.py:1890] channels=256 size=16384
[INFO 2017-03-07 09:38:06,478 layers.py:1890] output size for __conv_6__ is 8
[INFO 2017-03-07 09:38:06,479 layers.py:1985] output size for __pool_2__ is 4*4
[INFO 2017-03-07 09:38:06,480 layers.py:1890] channels=256 size=4096
[INFO 2017-03-07 09:38:06,481 layers.py:1890] output size for __conv_7__ is 4
[INFO 2017-03-07 09:38:06,483 layers.py:1890] channels=512 size=8192
[INFO 2017-03-07 09:38:06,483 layers.py:1890] output size for __conv_8__ is 4
[INFO 2017-03-07 09:38:06,485 layers.py:1890] channels=512 size=8192
[INFO 2017-03-07 09:38:06,485 layers.py:1890] output size for __conv_9__ is 4
[INFO 2017-03-07 09:38:06,487 layers.py:1985] output size for __pool_3__ is 2*2
[INFO 2017-03-07 09:38:06,488 layers.py:1890] channels=512 size=2048
[INFO 2017-03-07 09:38:06,488 layers.py:1890] output size for __conv_10__ is 2
[INFO 2017-03-07 09:38:06,490 layers.py:1890] channels=512 size=2048
[INFO 2017-03-07 09:38:06,490 layers.py:1890] output size for __conv_11__ is 2
[INFO 2017-03-07 09:38:06,491 layers.py:1890] channels=512 size=2048
[INFO 2017-03-07 09:38:06,491 layers.py:1890] output size for __conv_12__ is 2
[INFO 2017-03-07 09:38:06,493 layers.py:1985] output size for __pool_4__ is 1*1
[INFO 2017-03-07 09:38:06,495 networks.py:1466] The input order is [image, label]
[INFO 2017-03-07 09:38:06,495 networks.py:1472] The output order is [__cost_0__]
I0307 09:38:06.502377   355 Trainer.cpp:170] trainer mode: Normal
I0307 09:38:06.710746   355 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0307 09:38:06.712720   355 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0307 09:38:06.713508   355 GradientMachine.cpp:134] Initing parameters..
I0307 09:38:07.561144   355 GradientMachine.cpp:141] Init parameters done.
I0307 09:38:10.089026   364 ThreadLocal.cpp:37] thread use undeterministic rand seed:365
I0307 09:38:10.251857   357 ThreadLocal.cpp:37] thread use undeterministic rand seed:358
I0307 09:38:10.296422   356 ThreadLocal.cpp:37] thread use undeterministic rand seed:357
I0307 09:38:10.305033   359 ThreadLocal.cpp:37] thread use undeterministic rand seed:360
I0307 09:38:10.348325   358 ThreadLocal.cpp:37] thread use undeterministic rand seed:359
/usr/local/bin/paddle: line 109:   355 Killed                  ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by sunnysuhappy** [comment]
感觉没有什么有用信息啊，我是python弱弱= =

**Comment by gangliao** [comment]
自己编译的docker image还是直接pull的image

**Comment by qingqing01** [comment]
@sunnysuhappy  或许和 #77 问题类似，docker的内存太小了，可以调大一些~

**Comment by sunnysuhappy** [comment]
确实是内存的问题，调整到4G就可以了，谢谢支持
