### ISSUE TITLE
recognize_digits/*.md use \arg with softmax

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/book#164]
<img width="590" alt="screen shot 2017-03-07 at 4 41 17 pm" src="https://cloud.githubusercontent.com/assets/1548775/23684637/e90270d6-0354-11e7-9292-ed18beb90986.png">

In LaTeX, we should type `\arg{softmax}` instead of `softmax` to get the correct font.

**Comment by luotao1** [comment]
需要改成`\text{softmax}`

**Comment by luotao1** [comment]
@wangkuiyi correct font是指什么样的字体？目前是因为o和f之间有距离，还是别的原因？
