### ISSUE TITLE
Sudnya currently working on the Image classification EN readme

### ISSUE THREAD

**Issue by sudnya** [PaddlePaddle/book#195]
I am working on https://github.com/PaddlePaddle/book/blob/develop/image_classification/README.en.md

**Comment by helinwang** [comment]
Thank you! Greatly appreciated! We recently updated the tutorial, so please be sure to check for latest change :) (Now everyone has finished working on it, so it should be pretty stable.)

**Comment by luotao1** [comment]
Close this issue since there has english version of this chapter now.
