### ISSUE TITLE
Alloc fail in [03.image_classification]

### ISSUE THREAD

**Issue by jekin000** [PaddlePaddle/book#246]
I found an Alloc fail when I try VGG sample in [03.image_classification]

Error Message is:
[INFO 2017-03-21 05:45:27,928 networks.py:1472] The input order is [image, label]
[INFO 2017-03-21 05:45:27,928 networks.py:1478] The output order is [__classification_cost_0__]
I0321 05:45:28.071794   397 GradientMachine.cpp:86] Initing parameters..
I0321 05:45:28.876621   397 GradientMachine.cpp:93] Init parameters done.
Cache file /root/.cache/paddle/dataset/cifar/cifar-10-python.tar.gz not found, downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[==================================================]F0321 08:03:35.374790   397 Allocator.h:51] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fd7f88cae78  google::LogMessage::Fail()
    @     0x7fd7f88cadbf  google::LogMessage::SendToLog()
    @     0x7fd7f88ca734  google::LogMessage::Flush()
    @     0x7fd7f88cd929  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd7f8769e08  paddle::CpuAllocator::alloc()
    @     0x7fd7f8779626  paddle::PoolAllocator::alloc()
    @     0x7fd7f875de86  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7fd7f87802b1  paddle::CpuMatrix::CpuMatrix()
    @     0x7fd7f8780516  paddle::Matrix::create()
    @     0x7fd7f878d270  paddle::Matrix::resizeOrCreate()
    @     0x7fd7f85f55bc  paddle::BatchNormalizationLayer::forward()
    @     0x7fd7f867899e  paddle::NeuralNetwork::forward()
    @     0x7fd7f86554b3  paddle::GradientMachine::forwardBackward()
    @     0x7fd7f880c92a  GradientMachine::forwardBackward()
    @     0x7fd7f8530899  _wrap_GradientMachine_forwardBackward
    @           0x52714b  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x567d14  (unknown)
    @           0x465bf4  PyRun_FileExFlags
    @           0x46612d  PyRun_SimpleFileExFlags
    @           0x466d92  Py_Main
    @     0x7fd7f97fbf45  __libc_start_main
    @           0x577c2e  (unknown)
    @              (nil)  (unknown)

**Comment by jekin000** [comment]
[INFO 2017-03-21 05:45:27,928 networks.py:1472] The input order is [image, label]
[INFO 2017-03-21 05:45:27,928 networks.py:1478] The output order is [__classification_cost_0__]
I0321 05:45:28.071794   397 GradientMachine.cpp:86] Initing parameters..
I0321 05:45:28.876621   397 GradientMachine.cpp:93] Init parameters done.
Cache file /root/.cache/paddle/dataset/cifar/cifar-10-python.tar.gz not found, downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[==================================================]F0321 08:03:35.374790   397 Allocator.h:51] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fd7f88cae78  google::LogMessage::Fail()
    @     0x7fd7f88cadbf  google::LogMessage::SendToLog()
    @     0x7fd7f88ca734  google::LogMessage::Flush()
    @     0x7fd7f88cd929  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd7f8769e08  paddle::CpuAllocator::alloc()
    @     0x7fd7f8779626  paddle::PoolAllocator::alloc()
    @     0x7fd7f875de86  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7fd7f87802b1  paddle::CpuMatrix::CpuMatrix()
    @     0x7fd7f8780516  paddle::Matrix::create()
    @     0x7fd7f878d270  paddle::Matrix::resizeOrCreate()
    @     0x7fd7f85f55bc  paddle::BatchNormalizationLayer::forward()
    @     0x7fd7f867899e  paddle::NeuralNetwork::forward()
    @     0x7fd7f86554b3  paddle::GradientMachine::forwardBackward()
    @     0x7fd7f880c92a  GradientMachine::forwardBackward()
    @     0x7fd7f8530899  _wrap_GradientMachine_forwardBackward
    @           0x52714b  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x567d14  (unknown)
    @           0x465bf4  PyRun_FileExFlags
    @           0x46612d  PyRun_SimpleFileExFlags
    @           0x466d92  Py_Main
    @     0x7fd7f97fbf45  __libc_start_main
    @           0x577c2e  (unknown)
    @              (nil)  (unknown)

**Comment by jekin000** [comment]
paddlepaddle version is paddledev/paddle:0.10.0rc1-cpu

**Comment by jekin000** [comment]
And I run Ubuntu 1404 by  VMware.

**Comment by gongweibao** [comment]
The document is [here](https://github.com/PaddlePaddle/book/blob/develop/README.en.md)
The paddlepaddle dockerhub repository is [here](https://hub.docker.com/r/paddlepaddle/paddle/tags/)
You may use paddlepadle version paddlepaddle/paddle:0.10.0rc2 or paddlepaddle/paddle

**Comment by jekin000** [comment]
@gongweibao ，Thanks！ I will try it.

**Comment by gongweibao** [comment]
@jekin000, errno "12"  means "Out of memory"?  May be the vmware's memory is too small .

**Comment by jekin000** [comment]
@gongweibao not sure about that, where do you found "errno 12" ?

**Comment by gongweibao** [comment]
> Allocator.h:51] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0)

**Comment by jekin000** [comment]
@gongweibao ， Thanks！ And I will try 0.10.0rc2  first. By the way,  how  many memory required when I use paddlepaddle to run  03.image_classification.VGG ?

I just allocate 2GB to my Ubuntu VM. Is that enough?

**Comment by gongweibao** [comment]
may be 3g for [03.image_classification]

**Comment by jekin000** [comment]
ok, Thanks!

**Comment by jekin000** [comment]
It works , Thanks! @gongweibao
