### ISSUE TITLE
情感分析html中部分标题格式错误

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/book#253]
看了下html中的markdown语法是正确的，可能是渲染markdown语法时的问题。

![image](https://cloud.githubusercontent.com/assets/11692045/24279072/8de0b8b2-1082-11e7-8861-fdff9b4e4fd2.png)
![image](https://cloud.githubusercontent.com/assets/11692045/24279080/9d1fc00c-1082-11e7-8959-b5639810d870.png)

**Comment by cddesire** [comment]
![image](https://cloud.githubusercontent.com/assets/5432525/24434628/58516dc4-1463-11e7-8bcf-f69d606e9cf4.png)
