### ISSUE TITLE
windows-docker 下，单机直接运行 06.label_semantic_roles/trian.py报错

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#257]
windows-docker 下，单机直接运行 06.label_semantic_roles/trian.py
报错

> Pass 91, Batch 300, Cost 4.274895
Pass 91, Batch 400, Cost 5.956556
Pass 91, Batch 500, Cost 2.365294
Pass 92, Batch 0, Cost 4.295222
Pass 92, Batch 100, Cost 11.625301
Pass 92, Batch 200, Cost 2.934830
Pass 92, Batch 300, Cost 8.967397
Pass 92, Batch 400, Cost 2.054969
Pass 92, Batch 500, Cost 5.914911
Pass 93, Batch 0, Cost 1.655390
Thread [140425110587136] Backwarding __lstmemory_7__, __mixed_7__, __lstmemory_6__, __mixed_6__, __lstmemory_5__, __mixed_5__, __lstmemory_4__, __mixed_4__, _
_lstmemory_3__, __mixed_3__, __lstmemory_2__, __mixed_2__, __lstmemory_1__, __mixed_1__, __lstmemory_0__, __mixed_0__, __embedding_layer_1__, mark_data, __emb
edding_layer_0__, verb_data, __embedding_layer_7__, ctx_p2_data, __embedding_layer_6__, ctx_p1_data, __embedding_layer_5__, ctx_0_data, __embedding_layer_4__,
 ctx_n1_data, __embedding_layer_3__, ctx_n2_data, __embedding_layer_2__, word_data,
*** Aborted at 1490526248 (unix time) try "date -d @1490526248" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fb739a4368e) received by PID 759 (TID 0x7fb744d58700) from PID 967063182; stack trace: ***
    @     0x7fb744512890 (unknown)
    @     0x7fb739a4368e hl_avx_lstm_backward_one_sequence<>()
    @     0x7fb739a42e3b paddle::LstmCompute::backwardOneSequence<>()
    @     0x7fb739a42f7d paddle::LstmCompute::backwardBatch<>()
    @     0x7fb739a781e1 paddle::LstmLayer::backwardBatch()
    @     0x7fb739a78877 paddle::LstmLayer::backward()
    @     0x7fb739ac97e0 paddle::NeuralNetwork::backward()
    @     0x7fb739c5d34a GradientMachine::forwardBackward()
    @     0x7fb7399822c0 _wrap_GradientMachine_forwardBackward
    @     0x7fb74482f36c PyEval_EvalFrameEx
    @     0x7fb744830200 PyEval_EvalCodeEx
    @     0x7fb74482c04a PyEval_EvalFrameEx
    @     0x7fb744830200 PyEval_EvalCodeEx
    @     0x7fb74482c04a PyEval_EvalFrameEx
    @     0x7fb744830200 PyEval_EvalCodeEx
    @     0x7fb74482c04a PyEval_EvalFrameEx
    @     0x7fb74482c257 PyEval_EvalFrameEx
    @     0x7fb744830200 PyEval_EvalCodeEx
    @     0x7fb744830329 PyEval_EvalCode
    @     0x7fb744854a4a PyRun_FileExFlags
    @     0x7fb744855fd7 PyRun_SimpleFileExFlags
    @     0x7fb74486bf95 Py_Main
    @     0x7fb743a71b45 __libc_start_main
    @           0x4006ee (unknown)
    @                0x0 (unknown)
Floating point exception

**Comment by qingqing01** [comment]
这个问题和机器翻译一样，好在这个demo跑了93个Pass才出现FPE。

- 这个demo上一版对数据组batch有一定特殊处理，控制一个batch内的样本数总得word个数不超过150个，这版没有做这样做，采取的策略是减小了batch size。
- 因为这个demo训练集收费，只能把测试集当做训练集，所以Pass数调小一些，应该也没问题的。

统一的解决，可能还得需要能够支持clipping操作。 如果希望能够复现论文的结果，还得控制每个mini-batch的样本数。 另外，由于api支持还不够完善，这个demo其实还缺乏一些东西，可以后续一起完善了。
