### ISSUE TITLE
windows-docker 下，单机直接运行 03.image_classification/trian.py没能启动训练直接Killed

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#258]
>  python train.py
>I0326 23:52:29.501113   804 Util.cpp:160] commandline:  --use_gpu=False --trainer_count=1
[INFO 2017-03-26 23:52:29,509 layers.py:2106] output for __conv_0__: c = 64, h = 32, w = 32, size = 65536
[INFO 2017-03-26 23:52:29,511 layers.py:2106] output for __conv_1__: c = 64, h = 32, w = 32, size = 65536
[INFO 2017-03-26 23:52:29,513 layers.py:2230] output for __pool_0__: c = 64, h = 16, w = 16, size = 16384
[INFO 2017-03-26 23:52:29,514 layers.py:2106] output for __conv_2__: c = 128, h = 16, w = 16, size = 32768
[INFO 2017-03-26 23:52:29,517 layers.py:2106] output for __conv_3__: c = 128, h = 16, w = 16, size = 32768
[INFO 2017-03-26 23:52:29,518 layers.py:2230] output for __pool_1__: c = 128, h = 8, w = 8, size = 8192
[INFO 2017-03-26 23:52:29,518 layers.py:2106] output for __conv_4__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-03-26 23:52:29,519 layers.py:2106] output for __conv_5__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-03-26 23:52:29,520 layers.py:2106] output for __conv_6__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-03-26 23:52:29,521 layers.py:2230] output for __pool_2__: c = 256, h = 4, w = 4, size = 4096
[INFO 2017-03-26 23:52:29,522 layers.py:2106] output for __conv_7__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-03-26 23:52:29,523 layers.py:2106] output for __conv_8__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-03-26 23:52:29,524 layers.py:2106] output for __conv_9__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-03-26 23:52:29,525 layers.py:2230] output for __pool_3__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,526 layers.py:2106] output for __conv_10__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,527 layers.py:2106] output for __conv_11__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,528 layers.py:2106] output for __conv_12__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,531 layers.py:2230] output for __pool_4__: c = 512, h = 1, w = 1, size = 512
[INFO 2017-03-26 23:52:29,534 networks.py:1472] The input order is [image, label]
[INFO 2017-03-26 23:52:29,535 networks.py:1478] The output order is [__classification_cost_0__]
[INFO 2017-03-26 23:52:29,536 layers.py:2106] output for __conv_0__: c = 64, h = 32, w = 32, size = 65536
[INFO 2017-03-26 23:52:29,537 layers.py:2106] output for __conv_1__: c = 64, h = 32, w = 32, size = 65536
[INFO 2017-03-26 23:52:29,539 layers.py:2230] output for __pool_0__: c = 64, h = 16, w = 16, size = 16384
[INFO 2017-03-26 23:52:29,539 layers.py:2106] output for __conv_2__: c = 128, h = 16, w = 16, size = 32768
[INFO 2017-03-26 23:52:29,540 layers.py:2106] output for __conv_3__: c = 128, h = 16, w = 16, size = 32768
[INFO 2017-03-26 23:52:29,541 layers.py:2230] output for __pool_1__: c = 128, h = 8, w = 8, size = 8192
[INFO 2017-03-26 23:52:29,542 layers.py:2106] output for __conv_4__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-03-26 23:52:29,543 layers.py:2106] output for __conv_5__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-03-26 23:52:29,544 layers.py:2106] output for __conv_6__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-03-26 23:52:29,546 layers.py:2230] output for __pool_2__: c = 256, h = 4, w = 4, size = 4096
[INFO 2017-03-26 23:52:29,547 layers.py:2106] output for __conv_7__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-03-26 23:52:29,548 layers.py:2106] output for __conv_8__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-03-26 23:52:29,549 layers.py:2106] output for __conv_9__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-03-26 23:52:29,552 layers.py:2230] output for __pool_3__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,553 layers.py:2106] output for __conv_10__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,555 layers.py:2106] output for __conv_11__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,556 layers.py:2106] output for __conv_12__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-03-26 23:52:29,557 layers.py:2230] output for __pool_4__: c = 512, h = 1, w = 1, size = 512
[INFO 2017-03-26 23:52:29,559 networks.py:1472] The input order is [image, label]
[INFO 2017-03-26 23:52:29,559 networks.py:1478] The output order is [__classification_cost_0__]
I0326 23:52:29.609350   804 GradientMachine.cpp:86] Initing parameters..
I0326 23:52:30.362373   804 GradientMachine.cpp:93] Init parameters done.
Killed

**Comment by typhoonzero** [comment]
可以提供下Windows下docker-machine创建的虚拟机内存大小么？使用：`docker-machine inspect`

**Comment by llxxxll** [comment]
docker的虚拟内存是2G，cpu2个. 
docker-machine inspect 命令提示
> Error: No machine name(s) specified and no "default" machine exists

**Comment by typhoonzero** [comment]
@llxxxll 内存增大点试试呢？

**Comment by llxxxll** [comment]
内存和cpu加倍后问题解决。感谢~
