### ISSUE TITLE
Book功能完善

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/book#265]
请大家每人自行跑demo，如果问题简单可以自行完善，其他问题请补充到下面的问题收集。
- 目标
具备上一版所有功能，包括应用部分。

- 问题收集
    - 01.fit_a_line @jacquesqiao 
    - 02.recognize_digits	 @gangliao 
      - 缺少部分可以自己实现[模型保存 & 预测]
    - 03.image_classification	@qingqing01   #271 
       - 缺少部分可以自己实现[模型保存 & 预测]
    - 04.word2vec  @reyoung 
       * paddle.v2不能使用sparse update, Fixed by [this PR](https://github.com/PaddlePaddle/Paddle/pull/1745)
    - 05.understand_sentiment  @hedaoyuan 
      - 缺少部分可以自己实现[模型保存 & 预测]
    - 06.label_semantic_roles	@lcy-seso  @qingqing01  #273 
        - Evalutor需要支持    @reyoung 
        - 训练中test需要支持
    - 07.machine_translation	@luotao1 
        - beam_search还未封装（这部分有点难度）    @reyoung 
        - 之前v1训练好的模型还未转成v2的，且没有提供下载功能  [#1750](https://github.com/PaddlePaddle/Paddle/pull/1750) 已完成
    - 08.recommender_system  @livc 
        - 没问题

**Comment by wangkuiyi** [comment]
最好在这里明确一下每一章的负责人。

**Comment by luotao1** [comment]
机器翻译：
- beam_search还未封装（这部分有点难度）
- 之前v1训练好的模型还未转成v2的，且没有提供下载功能（这部分容易做）

**Comment by qingqing01** [comment]
@wangkuiyi  指定了每个章节的讲师~

**Comment by luotao1** [comment]
[v2 api打印两次配置](https://github.com/PaddlePaddle/Paddle/issues/1708)也和这个issue有关

**Comment by livc** [comment]
个性化推荐一章都能跑通，没有问题！
