### ISSUE TITLE
无法找到输出模型

### ISSUE THREAD

**Issue by jekin000** [PaddlePaddle/book#266]
您好！在运行03.image_classification.train.py结束后，无法找到输出模型。

paddle.v2.SGD.train也没有配置save_dir的参数，请问在哪里可以找到这个参数？

**Comment by Yancey0623** [comment]
Hi @jekin000 , You can save parameters using  [parameters.to_tar](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/parameters.py#L265)  such as https://github.com/PaddlePaddle/Paddle/blob/develop/demo/mnist/api_train_v2.py#L98

**Comment by jekin000** [comment]
@Yancey1989 ，谢谢！已经可以导出模型了， 请问如何做predict ? 看到很多v2的例子都没有predict这一步

**Comment by jekin000** [comment]
got it, Thanks a lot!
