### ISSUE TITLE
新手入门

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/book#3]
请先阅读[中文教程撰写统一标准](https://github.com/PaddlePaddle/book/wiki/中文教程撰写统一标准)。

要求：
- 时间节点：2016.12.26前提交临时版，2017.01.03前提交完整的第一版，2017.01.15前全部完成。
- 提交地址：[fit_a_line目录](https://github.com/PaddlePaddle/book/blob/develop/fit_a_line/)。
- 已有参考：[demo代码](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/introduction)，[Paddle文档](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/getstarted/basic_usage)。
- 背景介绍：放样本图例。
- 模型概览：介绍损失函数、fullyConnect。可以只写公式不画图。

**Comment by zhouxiao-coder** [comment]
PR #28 is created for this issue. Currently, it is just a placeholder.
