### ISSUE TITLE
book/03.image_classification/vgg.py dropout module wrong

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/book#328]
https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/vgg.py#L40

```
Traceback (most recent call last):
  File "train.py", line 91, in <module>
    main()
  File "train.py", line 37, in main
    net = vgg_bn_drop(image)
  File "/home/lizhao/book/03.image_classification/vgg.py", line 40, in vgg_bn_drop
    drop = paddle.networks.dropout(input=conv5, dropout_rate=0.5)
AttributeError: 'module' object has no attribute 'dropout'
```
According to 
https://github.com/PaddlePaddle/Paddle/blob/0beda8736ffcac80a95bea20f873d8972d2b5b5e/doc/api/v2/config/networks.rst#dropout_layer

This line should be 
```
drop = paddle.networks.dropout_layer(input=conv5, dropout_rate=0.5)
```

**Comment by livc** [comment]
Can we close this issue? @lcy-seso

**Comment by lcy-seso** [comment]
Yes, this bug has been fixed by this PR https://github.com/PaddlePaddle/Paddle/pull/2384, we can close this issue.
