### ISSUE TITLE
docker需要hyper-v虚拟化能力才能使用

### ISSUE THREAD

**Issue by Hitvz** [PaddlePaddle/book#344]
我安装完docker它就报错了，原因是我电脑不支持hyper-v虚拟化，希望能增加其他安装的方法咯，比如tensorflow教程里面的Anaconda方式安装就不错。环境在windows10下发生的，我只是提下问题和意见而已

**Comment by ShineByHui** [comment]
还有个问题，为什么这个demo文档要把最重要的ipyn文件，用.gitignore全部忽略掉呢。.ipynb后缀能download as其他格式，其它格式却不能download as **.ipynb文件，本想自己动手搭试试的，却发现没有.ipynb文件也是坑。

**Comment by ShineByHui** [comment]
看完编译安装的部分，我发觉这只有linux发行版版本，因为要用cmake，所以anaconda也救不了，所以官方选择了docker，用了下docker里面的jupyter notebook的命令行，发觉那就是linux，而且名字是moby，是docker公司的一个配置好环境的linux发行版。所以我还是老老实实用linux吧

**Comment by ShineByHui** [comment]
接着吧Dockerfile也加入忽略文件，那就是叫人不要构建这本book啊
