### ISSUE TITLE
房价程序运行错误（python2.7）

### ISSUE THREAD

**Issue by zgd716** [PaddlePaddle/book#345]
![2017-07-17_135913](https://user-images.githubusercontent.com/5136490/28256792-2abba3de-6af8-11e7-8584-3ffad71e042e.png)

**Comment by lcy-seso** [comment]
您好，这个错误是因为 Paddle develop 分支之前的commit引起的bug，可以参考这个issue，
https://github.com/PaddlePaddle/Paddle/issues/2908  。目前develope 分支已经修复了这个bug。

**Comment by zgd716** [comment]
你好，我是使用docker安装的，需要如何修复？


zhangguodong_12@126.com
 
发件人： Cao Ying
发送时间： 2017-07-17 16:38
收件人： PaddlePaddle/book
抄送： jellyzhang; Author
主题： Re: [PaddlePaddle/book] 房价程序运行错误（python2.7） (#345)
您好，这个错误是因为 Paddle develop 分支之前的commit引起的bug，可以参考这个issue，
PaddlePaddle/Paddle#2908 。目前develope 分支已经修复了这个bug。

**Comment by Yancey0623** [comment]
Hi, @TimLoveFreedom ，新的Book镜像正在build，https://hub.docker.com/r/paddlepaddle/book/tags/ latest的镜像更新了就可以用了，预计1-2h吧。

**Comment by lcy-seso** [comment]
谢谢啦 ~ @Yancey1989

**Comment by zgd716** [comment]
docker pull paddlepaddle/book 获取到的optimizer.py还不是最新的，请帮忙看一下镜像吧。。多谢

**Comment by lcy-seso** [comment]
- 有一个临时的解决方法，从 Paddle devlop 分支clone 最新的代码，然后用dev分支的`python/paddle/v2/optimizer.py` 覆盖docker环境下面`python/site-package/paddle/v2/optimizer.py`。
- 镜像的问题我们再检查一下。

**Comment by zgd716** [comment]
不好意思，镜像已经没问题了，多谢



zhangguodong_12@126.com
 
发件人： Cao Ying
发送时间： 2017-07-18 11:07
收件人： PaddlePaddle/book
抄送： jellyzhang; Mention
主题： Re: [PaddlePaddle/book] 房价程序运行错误（python2.7） (#345)
有一个临时的解决方法，从 Paddle devlop 分支clone 最新的代码，然后用dev分支的python/paddle/v2/optimizer.py 覆盖docker环境下面python/site-package/paddle/v2/optimizer.py。
镜像的问题我们再检查一下。
