### ISSUE TITLE
请教一下是否提供sum layer，以实现word2vec cbow

### ISSUE THREAD

**Issue by lujiaying** [PaddlePaddle/book#361]
book里提供的方法，4个词embedding之后，做concat，然后再softmax。
如果我想实现embedding之后sum/average，应该使用什么层呢？
linear_comb层吗？

**Comment by lcy-seso** [comment]
可以使用 add_to layer.
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L2941
