### ISSUE TITLE
请问生成的参数文件 params_pass_xx.tar 怎样读取参数？

### ISSUE THREAD

**Issue by mycamphortree** [PaddlePaddle/book#364]
with open('params_pass_%d.tar'%event.pass_id,'w') as f:
			parameters.to_tar(f)
把参数写进了文件，那么有了一个参数文件，怎样读参数给parameters呢？

**Comment by luotao1** [comment]
可以使用`from_tar`:
```
with open('params_pass_20.tar', 'r') as f:
    parameters = paddle.parameters.Parameters.from_tar(f)
```

**Comment by mycamphortree** [comment]
谢谢，还可以用parameters = parameters .init_from_tar(f)，应该本质上是一个函数
