### ISSUE TITLE
pass_id和batch_id的含义是什么？

### ISSUE THREAD

**Issue by mycamphortree** [PaddlePaddle/book#365]
第2课，数字识别中，从pass_id的输出结果来看，应该是训练器trainer设置的训练次数“num_passes”，但是batch_id是什么回事，明明trainer中设置的batch_size = 128，为啥batch_id可以达到400？

**Comment by luotao1** [comment]
batch_id是第几个batch的意思。batch_id * batch_size = 1个pass中的样本数。

**Comment by mycamphortree** [comment]
buf_size=8192
batch_size=128
buf_size / batch_size = 64
总共才64个batch吧，为什么batch_id可以到468？

源码：
 if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 100 == 0:
                print "Pass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics)

输出
....
Pass 0, Batch 466, Cost 0.126535, {'classification_error_evaluator': 0.0234375}
Pass 0, Batch 467, Cost 0.032776, {'classification_error_evaluator': 0.0234375}
Pass 0, Batch 468, Cost 0.064163, {'classification_error_evaluator': 0.03125}
Test with Pass 0, Cost 0.068953, {'classification_error_evaluator': 0.0228000003}
每一个pass的batch_id都会达到468，请问这个468是怎样来的？

**Comment by luotao1** [comment]
buf_size是buffer_size的缩写，是每次读多少条进入内存，不是真实的样本数。真实的样本数是paddle.dataset.mnist.train()的条数，即mnist训练集的样本数。

**Comment by mycamphortree** [comment]
理解了，谢谢
