### ISSUE TITLE
浏览器无法打开http://localhost:8888/

### ISSUE THREAD

**Issue by rambowding** [PaddlePaddle/book#368]
按下面运行了这个docker image
<img width="740" alt="fb1bf36e5b24019d7d8aa3e7a5952970" src="https://user-images.githubusercontent.com/7675778/29965399-00cb0af8-8f40-11e7-8f8a-038d013fa157.png">
但在浏览器中http://localhost:8888/一直打不开可能是啥原因？

**Comment by typhoonzero** [comment]
执行`docker logs 1cc`看下日志呢？

**Comment by wwlaoxi** [comment]
查看装有paddlepaddle镜像的docker容器是否启动，只要启动了就能正常打开。

**Comment by rambowding** [comment]
@typhoonzero 
rambow@rambow-ubuntu:~$ docker logs 1cc
[I 12:55:39.789 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 12:55:39.855 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 12:55:39.905 NotebookApp] Serving notebooks from local directory: /book
[I 12:55:39.905 NotebookApp] 0 active kernels 
[I 12:55:39.905 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/
[I 12:55:39.906 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

**Comment by rambowding** [comment]
@wwlaoxi 
docker不会，按我的理解，下面这句不就是启动么？

rambow@rambow-ubuntu:~$  docker run -d -p 8888:8888 paddlepaddle/book
a6e779dedf7be909f5a5fb7d0c7fc320d9593078f3a59b5535fbce6ee9295543
rambow@rambow-ubuntu:~$

**Comment by rambowding** [comment]
@wwlaoxi 
docker不会，按我的理解，下面这句不就是启动么？
rambow@rambow-ubuntu:~$ docker run -d -p 8888:8888 paddlepaddle/book
a6e779dedf7be909f5a5fb7d0c7fc320d9593078f3a59b5535fbce6ee9295543
rambow@rambow-ubuntu:~$

**Comment by rambowding** [comment]
[I 12:55:39.905 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/
这个地址是不是有问题？

**Comment by typhoonzero** [comment]
@rambowding 看日志，book是正确启动的`http://0.0.0.0:8888/`是book监听的地址。如果无法访问，建议查看docker是否正确配置了iptables的NAT表提供了端口转发，也可以使用`telnet localhost 8888`测试端口是否正常。

**Comment by rambowding** [comment]
@typhoonzero 
![screenshot from 2017-09-06 20 29 14](https://user-images.githubusercontent.com/7675778/30111932-2d7fe5f4-9342-11e7-8314-945cf3a7ff0e.png)
有啥问题？

**Comment by typhoonzero** [comment]
看上去端口是可以访问的。所以，“一直打不开”具体现象是什么。notebook是正常运行的，这个应该是其他的问题了。

**Comment by rambowding** [comment]
@typhoonzero 就和普通网页打不开一样
![screenshot from 2017-09-11 19 57 29](https://user-images.githubusercontent.com/7675778/30273451-9a238656-972b-11e7-8d8e-86d29fb74d76.png)

**Comment by wwlaoxi** [comment]
1、先安装好docker
2、PADDLEPADDLE官网中的
新手入门 > 安装与编译 > PaddlePaddle的Docker容器使用方式 中的 运行PaddlePaddle Book
 运行这个命令就可以下载PaddlePaddle Book的Docker镜像

docker run -p 8888:8888 paddlepaddle/book

注意：为了方便在国内的开发者下载Docker镜像，我们提供了国内的镜像服务器供大家使用。如果您在国内，请把文档里命令中的paddlepaddle/paddle替换成docker.paddlepaddle.org/paddle。
3、使用docker的相关指令 docker images（在管理员模式下）查询镜像，如果有paddlepaddle/book的镜像说明安装成功
4、此时输入http://localhost:8888/就可以了。
5、以后每次运行时，需要首先在docker里运行安装该镜像的容器，在输入网址就可以了。运行docker的相关命令在网上可以查询到

**Comment by yeyupiaoling** [comment]
不用localhost试试，直接用你的IP地址

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
