### ISSUE TITLE
任务失败报找不到实际存在的文件

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/book#371]
Wed Sep  6 11:48:09 2017[1,5]<stderr>:F0906 11:48:09.745483 21400 PythonUtil.h:333] Check failed: (data) != nullptr Current PYTHONPATH: ['/home/normandy/maybach/286039/workspace', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/normandy/maybach/286039/workspace/paddle', '/home/normandy/maybach/286039/workspace', '/home/normandy/maybach/286039/workspace/thirdparty/thirdparty', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python27.zip', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7/plat-linux2', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7/lib-tk', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7/lib-old', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7/lib-dynload', '/home/normandy/maybach/286039/workspace/python27-gcc482/lib/python2.7/site-packages']
Wed Sep  6 11:48:09 2017[1,5]<stderr>:Python Error: <type 'exceptions.IOError'> : [Errno 2] No such file or directory: './test_data_dir/test/part-00151-B'

但实际看test_data_dir/test目录下，存在part-00151-B的文件

**Comment by luotao1** [comment]
经过沟通，是由于磁盘满了，导致无法从HDFS上下载文件。
