### ISSUE TITLE
运行房价预测的代码报错: AttributeError: 'module' object has no attribute 'mse_cost'

### ISSUE THREAD

**Issue by LNeway** [PaddlePaddle/book#372]
`AttributeErrorTraceback (most recent call last)
<ipython-input-1-fc4a5e973078> in <module>()
     73 
     74 if __name__ == '__main__':
---> 75     main()

<ipython-input-1-fc4a5e973078> in main()
     11     y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())
     12     y = paddle.layer.data(name='y', type=paddle.data_type.dense_vector(1))
---> 13     cost = paddle.layer.mse_cost(input=y_predict, label=y)
     14 
     15     # create parameters

AttributeError: 'module' object has no attribute 'mse_cost'
`

请问这个怎么解决

**Comment by typhoonzero** [comment]
Seems we have renamed `mse_cost` to `square_error_cost` due to the implementation details: https://github.com/PaddlePaddle/Paddle/pull/3845, will fix.
Anyway, you can change it to `square_error_cost` in the code to run for now.
