### ISSUE TITLE
最新的paddlepaddle/book:latest-gpu中代码不是最新

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/book#377]
/book/01.fit_a_line/train.py  这个代码中用到了
```python
cost = paddle.layer.mse_cost(input=y_predict, label=y)
```
mse_cost已经本改名了，所以会失败，最新的book中的代码是对的，可能是没有打包到docker image中

**Comment by typhoonzero** [comment]
Already fixed in https://github.com/PaddlePaddle/book/pull/373, the docker image will be updated after nightly build.
