### ISSUE TITLE
Make CI test example programs

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/book#396]
According to the [configuration file](https://github.com/PaddlePaddle/book/blob/develop/.travis.yml), currently, the Travis CI does only precommit check:

```json
script:
  -  PATH=/tmp/go/bin:$PATH .travis/precommit.sh
```

where the [precommit.sh](https://github.com/PaddlePaddle/book/blob/develop/.travis/precommit.sh) file runs `pre-commit run -a`, which, according to the [pre-commit configuration file](https://github.com/PaddlePaddle/book/blob/develop/.pre-commit-config.yaml), does only format checking.

Can we make it call https://github.com/PaddlePaddle/book/blob/develop/.tools/convert-markdown-into-ipynb-and-test.sh to extract Python example code out from each chapter -- those directories with a numeric prefix, e.g., `01.fit_a_line/README.md`, and run them?

**Comment by putcn** [comment]
just tried this setting in travis, it's going to take too long to run through all of them, like the word2vect is going to take hours. Zhihong said even GPU machine will take at least hours. are we still going to run these tests?

**Comment by putcn** [comment]
closing this issue due to the execution time of all example
