### ISSUE TITLE
识别数字

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/book#4]
请先阅读[中文教程撰写统一标准](https://github.com/PaddlePaddle/book/wiki/中文教程撰写统一标准)。

要求：
- 时间节点：2016.12.26前提交临时版，2017.01.03前提交完整的第一版，2017.01.15前全部完成。
- 提交地址：[recognize_digits目录](https://github.com/PaddlePaddle/book/blob/develop/recognize_digits/)。
- 已有参考：[demo代码](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/mnist)，[tensorflow文档](https://www.tensorflow.org/tutorials/mnist/beginners/)。
- 模型概览：需要写MLP、CNN和Softmax的介绍和原理，要放图。

**Comment by dayhaha** [comment]
确认认领。
