### ISSUE TITLE
pip install paddlepaddle失败

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/book#424]
运行pip install paddlepaddle提示：
Could not find a version that satisfies the requirement paddlepaddle (from versions: )
No matching distribution found for paddlepaddle

运行pip install --upgrade pip后再install，依然出现上述问题

**Comment by typhoonzero** [comment]
paddlepaddle目前支持可以支持的python环境为:

python 2.7.x
Linux x86_64 / MacOS

另外，可以执行`python -c "import pip; print(pip.pep425tags.get_supported())"` 获取当前系统支持的架构，然后看下在pypi上是否存在。

**Comment by 333caowei** [comment]
python -c "import pip; print(pip.pep425tags.get_supported())"
[('cp27', 'cp27mu', 'linux_x86_64'), ('cp27', 'none', 'linux_x86_64'), ('py2', 'none', 'linux_x86_64'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]

**Comment by typhoonzero** [comment]
你的pip支持的格式是`linux_x86_64` 而pip 9.0.1支持的是`manylinux1_x86_64`，请确保升级到最新的pip。
