### ISSUE TITLE
AttributeError: 'module' object has no attribute 'square_error_cost'

### ISSUE THREAD

**Issue by shincfk** [PaddlePaddle/book#429]
root@b402efa66f54:/home/work# python train.py
I0928 09:21:58.518064    86 Util.cpp:166] commandline:  --use_gpu=False 
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    main()
  File "train.py", line 80, in main
    cost = paddle.layer.square_error_cost(
AttributeError: 'module' object has no attribute 'square_error_cost'
root@b402efa66f54:/home/work# 

>How to solve this question?

**Comment by typhoonzero** [comment]
Try update to the latest paddle please.

**Comment by shincfk** [comment]
I have solved this question. but your docker versions should update
