### ISSUE TITLE
初始化paddle时报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/book#434]
在执行这一行代码是就会报错：`paddle.init(use_gpu=False, trainer_count=1)`
报错信息是：The kernel appears to have died. It will restart automatically.
也不知道是哪里出错，在哪里可以看详细的报错信息？谢谢

**Comment by llxxxll** [comment]
是在notebook里执行的吗？

**Comment by yeyupiaoling** [comment]
@llxxxll 对啊，我在Windows搭建的，可以运行，但是一但执行代码，就出错了

**Comment by yeyupiaoling** [comment]
找到原因了，是因为我的电脑不支持AVX
