### ISSUE TITLE
在“book”中的“数字识别”如何使用已训练的模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/book#437]
在[数字识别](https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/README.cn.md)这章中，每次都有从零开始训练，太慢了，能不能使用之前已经训练过的模型

**Comment by llxxxll** [comment]
fix:https://github.com/PaddlePaddle/Paddle/issues/5080

**Comment by yeyupiaoling** [comment]
```
 with open("model/2/model.tar", 'r') as f:
      parameters = paddle.parameters.Parameters.from_tar(f)
```
