### ISSUE TITLE
paddle:0.10.0-dev镜像中跑01.fit_a_line中train.py提示ImportError: No module named paddle.v2

### ISSUE THREAD

**Issue by hoollywood** [PaddlePaddle/book#438]
步骤是在mac版本docker下载了paddle:0.10.0-dev镜像
然后执行demo中的python脚本：

执行命令如下：
docker run -it --rm -v /paddle:/workspace docker.paddlepaddle.org/paddle:0.10.0-dev   python /workspace/train.py
报错如下：
Traceback (most recent call last):
  File "/workspace/train.py", line 2, in <module>
    import paddle.v2 as paddle
ImportError: No module named paddle.v2

**Comment by Xreki** [comment]
请参考https://github.com/PaddlePaddle/Paddle/issues/4861
