### ISSUE TITLE
寻求paddlepaddle自动桃子分拣器图片、代码

### ISSUE THREAD

**Issue by breaknormal1** [PaddlePaddle/book#458]
看到有报道基于paddlepaddle的桃子分拣器
http://prnews.techweb.com.cn/qiyenews/archives/37698.html
“这 4 位学生已将所有代码和材料清单，上传至 GitHub 进行开源和分享，请全世界关注农业和关注深度学习的人共同完善”
paddle的同志们，你们知道这些code和材料在GitHub分享网址吗？
谢谢

**Comment by luotao1** [comment]
您好，谢谢您对我们桃子分拣器的关注，代码和材料可参考 https://github.com/4luojing/sorting4peach

**Comment by breaknormal1** [comment]
非常感谢
