### ISSUE TITLE
个性化推荐demo报错：'module' object has no attribute 'square_error_cost'

### ISSUE THREAD

**Issue by wzh420** [PaddlePaddle/book#470]
cost = paddle.layer.square_error_cost(
AttributeError: 'module' object has no attribute 'square_error_cost'

**Comment by will-am** [comment]
可能用的是老版本的paddle，老版本里这个cost 叫mse_cost，现在重名为square_error_cost

**Comment by wzh420** [comment]
更新最新版就好了
