### ISSUE TITLE
paddlepaddle 使用mpi训练batch模型报错Connection timed out

### ISSUE THREAD

**Issue by bigshipbig** [PaddlePaddle/book#476]
Sat Dec 30 07:39:58 2017[1,158]<stderr>:F1230 07:39:58.004369 48789 SocketChannel.cpp:56] Check failed: len >= 0  peer=10.89.144.34: Connection timed out [110]
![image](https://user-images.githubusercontent.com/15210529/34483359-e4b8af9a-eff8-11e7-9920-9a5b646d598b.png)

**Comment by typhoonzero** [comment]
Mark duplicated to https://github.com/PaddlePaddle/Paddle/issues/7146
