### ISSUE TITLE
如何实现自定义loss?

### ISSUE THREAD

**Issue by sonack** [PaddlePaddle/book#478]
paddlepaddle新手, 请问各位大佬如何在pdpd中实现自定义的loss呢?
paddlepaddle有类似于pytorch的autograd功能吗

**Comment by lcy-seso** [comment]
自定义损失函数在Paddle V2 版本不支持。可以做的是通过 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/op.py 这里面的一些基础数学运行进行组合。

自定义损失函数和autograd在Fluid可以实现，但现在文档建设并没有完成，我担心自己摸索和学习需要一些时间。

**Comment by sonack** [comment]
@lcy-seso  谢谢! 我看了下这些op, 只是一些很基础的数学运算op, 是不是没有像tensorflow里面的`tf.cond`一样的op来实现有条件的loss定义, 那么我怎么实现这样的有控制流逻辑的loss的定义呢? 有没有可以覆盖backward的函数什么的

**Comment by lcy-seso** [comment]
我上面发的链接是Paddle V2 的文档，你提到的这些功能在Fluid会支持。

目前Fluid的文档有下面这些链接，
Desing： https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/fluid.md
这个文件夹下有其他的design doc： https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design

API/operators 文档：
http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid.html  http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid.html

已有示例，https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/v2/fluid/tests/book

有可能这些文档对想要学习和使用还是不足够。祝好~

**Comment by sonack** [comment]
@lcy-seso  非常感谢
