### ISSUE TITLE
mnist手写体识别的那个示例怎么坏了？

### ISSUE THREAD

**Issue by lifubang** [PaddlePaddle/book#479]
root@cb462c7b76b1:/opt# **git clone https://github.com/PaddlePaddle/book**
正克隆到 'book'...
remote: Counting objects: 4782, done.
remote: Total 4782 (delta 0), reused 0 (delta 0), pack-reused 4782
接收对象中: 100% (4782/4782), 33.64 MiB | 281.00 KiB/s, 完成.
处理 delta 中: 100% (3156/3156), 完成.
检查连接... 完成。
root@cb462c7b76b1:/opt# **cd book/**
root@cb462c7b76b1:/opt/book# **ls**
01.fit_a_line            05.recommender_system    index.cn.html  pending
02.recognize_digits      06.understand_sentiment  index.html     README.cn.md
03.image_classification  07.label_semantic_roles  mnist-client   README.md
04.word2vec              08.machine_translation   paddle         serve
root@cb462c7b76b1:/opt/book# **cd 02.recognize_digits/**
root@cb462c7b76b1:/opt/book/02.recognize_digits# **ls**
client  image  index.cn.html  index.html  README.cn.md  README.md  train.py
root@cb462c7b76b1:/opt/book/02.recognize_digits# **python2 train.py** 
I0122 08:59:13.437571   121 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2018-01-22 08:59:13,443 layers.py:2689] output for __conv_pool_0___conv: c = 20, h = 24, w = 24, size = 11520
[INFO 2018-01-22 08:59:13,444 layers.py:2829] output for __conv_pool_0___pool: c = 20, h = 12, w = 12, size = 2880
[INFO 2018-01-22 08:59:13,445 layers.py:2689] output for __conv_pool_1___conv: c = 50, h = 8, w = 8, size = 3200
[INFO 2018-01-22 08:59:13,446 layers.py:2829] output for __conv_pool_1___pool: c = 50, h = 4, w = 4, size = 800
I0122 08:59:13.449390   121 GradientMachine.cpp:94] Initing parameters..
I0122 08:59:13.451611   121 GradientMachine.cpp:101] Init parameters done.
Pass 0, Batch 0, Cost 2.836447, {'classification_error_evaluator': 0.875}
Pass 0, Batch 100, Cost 2.305167, {'classification_error_evaluator': 0.875}
Pass 0, Batch 200, Cost 2.305494, {'classification_error_evaluator': 0.890625}
Pass 0, Batch 300, Cost 2.297118, {'classification_error_evaluator': 0.859375}
Pass 0, Batch 400, Cost 2.316209, {'classification_error_evaluator': 0.9140625}
Test with Pass 0, Cost 2.302148, **{'classification_error_evaluator': 0.8865000009536743}**

Pass 1, Batch 0, Cost 2.303937, {'classification_error_evaluator': 0.890625}
Pass 1, Batch 100, Cost 2.302149, {'classification_error_evaluator': 0.90625}
Pass 1, Batch 200, Cost 2.302109, {'classification_error_evaluator': 0.890625}
Pass 1, Batch 300, Cost 2.300121, {'classification_error_evaluator': 0.9140625}
Pass 1, Batch 400, Cost 2.293390, {'classification_error_evaluator': 0.859375}
Test with Pass 1, Cost 2.302162, **{'classification_error_evaluator': 0.8971999883651733}**

Pass 2, Batch 0, Cost 2.299892, {'classification_error_evaluator': 0.8984375}
Pass 2, Batch 100, Cost 2.308000, {'classification_error_evaluator': 0.8984375}
Pass 2, Batch 200, Cost 2.301318, {'classification_error_evaluator': 0.9140625}
Pass 2, Batch 300, Cost 2.300943, {'classification_error_evaluator': 0.859375}
Pass 2, Batch 400, Cost 2.313893, {'classification_error_evaluator': 0.953125}
Test with Pass 2, Cost 2.302042, **{'classification_error_evaluator': 0.8971999883651733}**

Pass 3, Batch 0, Cost 2.294420, {'classification_error_evaluator': 0.84375}
Pass 3, Batch 100, Cost 2.325497, {'classification_error_evaluator': 0.9296875}
Pass 3, Batch 200, Cost 2.296998, {'classification_error_evaluator': 0.8671875}
Pass 3, Batch 300, Cost 2.294434, {'classification_error_evaluator': 0.8515625}
Pass 3, Batch 400, Cost 2.301574, {'classification_error_evaluator': 0.859375}
Test with Pass 3, Cost 2.301726, **{'classification_error_evaluator': 0.8971999883651733}**

Pass 4, Batch 0, Cost 2.316931, {'classification_error_evaluator': 0.921875}
Pass 4, Batch 100, Cost 2.304905, {'classification_error_evaluator': 0.921875}
Pass 4, Batch 200, Cost 2.294854, {'classification_error_evaluator': 0.859375}
Pass 4, Batch 300, Cost 2.303220, {'classification_error_evaluator': 0.8671875}
Pass 4, Batch 400, Cost 2.307637, {'classification_error_evaluator': 0.890625}
Test with Pass 4, Cost 2.302750, **{'classification_error_evaluator': 0.8971999883651733}**

Best pass is 3, testing Avgcost is 2.30172612419
The classification accuracy is 10.28%
Label of image/infer_3.png is: 7
root@cb462c7b76b1:/opt/book/02.recognize_digits#

**Comment by lifubang** [comment]
@gangliao @QiJune @wangkuiyi @helinwang @pengli09 @alexqdh 
怎么'classification_error_evaluator': 0.8971999883651733，一直是这个？
最后infer_3.png识别为7？

看过程我是git clone下来的，代码都没改。哪里错了吗？

**Comment by Xreki** [comment]
你好，所有图片的infer结果都不对吗？

**Comment by lifubang** [comment]
训练一次时间挺长的，其他的我没试。

> 训练之后，检查模型的预测准确度。用 MNIST 训练的时候，一般 softmax回归模型的分类准确率为约为 92.34%，多层感知器为97.66%，卷积神经网络可以达到 99.20%。

不是说能达到99.20%吗？怎么最后一只是0.897？
