### ISSUE TITLE
docker运行提示权限不够

### ISSUE THREAD

**Issue by LGinC** [PaddlePaddle/book#481]
~/works$ docker run -it -v $PWD:/work paddlepaddle/paddle /work/train.py
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/work/train.py\\\": permission denied\"\n".``

**Comment by typhoonzero** [comment]
Try `docker run -it -v $PWD:/work paddlepaddle/paddle python /work/train.py`
