### ISSUE TITLE
05.recommender_system使用GPU时报错Matrix.cpp:652] Not supported

### ISSUE THREAD

**Issue by sunandsky1992** [PaddlePaddle/book#484]
在GPU上运行05.recommender_system时报错

**Comment by JiayiFeng** [comment]
在recommender_system的样例中有一个类型为sparse_binary_vector的输入（ https://github.com/PaddlePaddle/book/blob/develop/05.recommender_system/train.py#L52 ），目前GPU环境下还不支持该类型的输入，因此会报错。recommender_system本身的计算都是可以在GPU上运行的，可以考虑换成其他类型的输入。
