### ISSUE TITLE
typo in 02.recognize_digits fig. 4

### ISSUE THREAD

**Issue by wanglun** [PaddlePaddle/book#502]
![image](https://user-images.githubusercontent.com/143647/37700624-3cae018a-2d27-11e8-94a8-333dfc3d5bd7.png)

https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/image/conv_layer.png

**Comment by shanyi15** [comment]
get, thank you for your suggestion, we'll look into it.

**Comment by shanyi15** [comment]
hi 请问您可以在issue里填一下此图的地址/链接吗
感谢！

**Comment by wanglun** [comment]
已补充图片链接

**Comment by shanyi15** [comment]
已修改，感谢您反馈
