### ISSUE TITLE
paddle book机器翻译BLEU值

### ISSUE THREAD

**Issue by hjchen2** [PaddlePaddle/book#511]
我按照paddle book上机器翻译的例子用作者提供的训练好的模型进行预测，并计算了一下BLEU值，发现这个BLEU值与作者说的26.92差距太大，我测出来是3.37。请问是什么问题呢？

paddle book NMT的链接： http://paddlepaddle.org/docs/develop/book/08.machine_translation/index.cn.html

**Comment by luotao1** [comment]
closed due to https://github.com/PaddlePaddle/Paddle/issues/9983
