### ISSUE TITLE
请问paddle中对于load embeding的oov有设置初始化值的参数吗？

### ISSUE THREAD

**Issue by bbgasj** [PaddlePaddle/book#543]
load embeding对于nlp任务应该是很常见的操作，一般初始化要么设全0，要么设置一个均值为0的正太分布，但是了解到ParameterAttribute里面的initial_*相关参数只在初始化的时候会用到，load已有词向量的话不生效。
对于nlp任务，这应该是一个比较常见的操作，建议支持一下。

**Comment by bbgasj** [comment]
https://github.com/PaddlePaddle/Paddle/issues/11361
挪到这里

**Comment by Yancey0623** [comment]
Thanks, will close this issue and follow https://github.com/PaddlePaddle/Paddle/issues/11361
