### ISSUE TITLE
dssm双塔损失函数

### ISSUE THREAD

**Issue by zachzh** [PaddlePaddle/book#566]
看dssm电影推荐那个例子，我的目的是想得到vector，demo里损失函数是用的mse，但是我label里只有0和1，请问下paddle能实现如下的损失函数吗？用的是v2版本
![image](https://user-images.githubusercontent.com/2037256/42455063-cc8821e4-83c3-11e8-9a3e-0f6d0e816bc7.png)

**Comment by AIpioneer** [comment]
您好，现在v2版本已经不维护了，建议使用最新版本
