### ISSUE TITLE
PaddlePaddle book使用体验总结

### ISSUE THREAD

**Issue by chenwhql** [PaddlePaddle/book#575]
### 使用感受
- 优点：绝大部分例程均正确执行，配合图文讲解，易于理解
- 缺点：个别例程存在一些问题，建议完善一些文字与结果描述的细节

##### JupyterNoteBook版本（CPU & GPU）
- 根据文档建议，运行  
`docker run -d -p 8888:8888 paddlepaddle/book`  
或  
`nvidia-docker run -d -p 8888:8888 paddlepaddle/book:latest-gpu`  
然后在Jupyter Notebook中结合教程运行
##### Fluid Docker版本（CPU & GPU）：
- 根据官网Paddle安装建议，使用docker安装GPU版本镜像  
`docker pull paddlepaddle/paddle:latest-gpu`  
然后在docker中执行PaddlePaddle book的train.py脚本

##### JupyterNoteBook版本（CPU）：成功
- 完善建议：[注释完善、测试结果、显存占用等](https://github.com/PaddlePaddle/book/issues/572)
##### JupyterNoteBook版本（CPU）：成功
- 完善建议： [文档表述完善、测试结果等](https://github.com/PaddlePaddle/book/issues/569)
##### JupyterNoteBook版本（CPU）：成功
- 完善建议：[词汇使用、图片标题显示、测试结果等](https://github.com/PaddlePaddle/book/issues/567)
##### JupyterNoteBook版本（CPU）：成功
- 完善建议：[误用Code格式、测试结果等](https://github.com/PaddlePaddle/book/issues/568)
##### JupyterNoteBook版本（CPU）：成功
- 完善建议：[结尾未打印测试结果](https://github.com/PaddlePaddle/book/issues/571)
##### Fluid Docker版本（CPU）：成功
- 完善建议：[result显示格式意义不明](https://github.com/PaddlePaddle/book/issues/571)
##### JupyterNoteBook版本（CPU）
- 运行结果：
    - convolution_net：**失败**，[【bug】inferencer未成功创建](https://github.com/PaddlePaddle/book/issues/570)
    - stacked_lstm_net：**缺少参数**
- 完善建议：[图片标题居中](https://github.com/PaddlePaddle/book/issues/570)
##### Fluid Docker版本（CPU）
- 运行结果：
    - convolution_net：成功
    - dyn_rnn_net: 成功
    - stacked_lstm_net: 成功
##### Fluid Docker版本（GPU）
- 运行结果：
    - convolution_net：成功
    - dyn_rnn_net: 成功
    - stacked_lstm_net: 成功

##### JupyterNoteBook版本（CPU）：成功
- 完善建议：[图片标题居中、二次执行报错等](https://github.com/PaddlePaddle/book/issues/573)
##### JupyterNoteBook版本（CPU）：成功
- 完善建议：[公式格式等](https://github.com/PaddlePaddle/book/issues/574)
### 综合建议
1. 是否可以完善jupyter Notebook版本的格式问题（均已在issue中提出）
    - 标题未居中（8个教程均存在）
    - 部分code与description的格式混乱（04）
> 作为一个普通用户，会优先按照首页README的使用描述 ，进入docker体验例程，所以需要优先保证jupyter Notebook版本的易用性和专业性，及时同步

2. 是否可以对于最后的预测结果做下简要的解释
    - （01-08均可以完善）
> 实验中最后的预测结果往往是一对数字，并没有给出有意义的解释，因为这里的例程带有一定教学性质，解释不充分对于用户理解来说是不太友好的

3. 对于用户开发的简洁性优化
> book中例如param_dirname的部分应通过封装避免用户重复输入相同的文件后缀名如".inference.model"

**Comment by xsrobin** [comment]
多谢反馈，我们会尽快参考您的建议优化文档。希望您能给我们的文档提更多的宝贵意见。

**Comment by zhengxijiang** [comment]
PaddlePaddle book使用，哪里正常？HTML打都打不开，一堆报错，难道我安装的这个book是假的？

**Comment by chenwhql** [comment]
> PaddlePaddle book使用，哪里正常？HTML打都打不开，一堆报错，难道我安装的这个book是假的？

您好，这个使用体验总结是2018年7月份测试的结果，在过去的一年半时间里，Paddle book进行了多次修改，这个测试结果已经不具备太大的参考价值了，如果您遇到使用问题，欢迎通过issues反馈具体的使用问题，谢谢，这个issue也早应该关闭了
