### ISSUE TITLE
启动paddlepaddle/book的image后，无法访问jupyter notebook页面

### ISSUE THREAD

**Issue by duanlin0505** [PaddlePaddle/book#610]
启动方法：
docker run -d -p 8888:8888 docker.paddlepaddlehub.com/book

查看的启动结果：
C:\>docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
a79b59a7d0a2        docker.paddlepaddlehub.com/book   "sh -c 'jupyter note"   23 minutes ago      Up 23 minutes       0.0.0.0:8888->8888/tcp   sad_williams
![image](https://user-images.githubusercontent.com/12709352/44766608-d5784400-ab8c-11e8-99c5-7a948b99ae11.png)

之后访问http://localhost:8888，显示ERR_CONNECTION_REFUSED

![image](https://user-images.githubusercontent.com/12709352/44766747-84b51b00-ab8d-11e8-9c29-155f33761ca4.png)

**Comment by velconia** [comment]
Have you followed [this](http://stackoverflow.com/a/39720010/724872) to install docker?

**Comment by duanlin0505** [comment]
我是在windows7的系统安装的docker，连接里说明的是mac的配置。
问题还是不一样的

**Comment by velconia** [comment]
> If you are using Windows or Mac, you might want to give Docker more memory and CPUs/cores.

**Comment by duanlin0505** [comment]
调整为3G ram, 2 cpu后，问题仍然存在

**Comment by duanlin0505** [comment]
![image](https://user-images.githubusercontent.com/12709352/44900690-d7323b00-ad37-11e8-8197-d02295bab303.png)

问题已经解决，原因如上图，需要在vm里设置一下端口服务
希望对大家有帮助
