### ISSUE TITLE
mac docker下运行cd data && python prepare_data.py 报错

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#63]
貌似因为mac os Sierra默认不支持matplotlib
解决方法如下：
安装matplotlib
`pip install matplotlib`
报错
`* The following required packages can not be built:Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8UvQcW/matplotlib`

解决方法，先执行
`sudo apt-get install libfreetype6-dev pkg-config`
再安装matplotlib
`pip install matplotlib`

最后执行
`cd data && python prepare_data.py `
提示
`housing.data  housing.test.npy  housing.train.npy  prepare_data.py  test.list  train.lis`

Done.

**Comment by wangkuiyi** [comment]
@llxxxll 你描述的问题是关于mac的，但是解法里有 apt-get install —— 这个命令是Linux里才有的？
