### ISSUE TITLE
运行paddle v2 serve的测试用例，出现core dump

### ISSUE THREAD

**Issue by LiuZheng-Z** [PaddlePaddle/book#640]
测试paddle v2的serving程序，用例[demo](https://github.com/PaddlePaddle/book/blob/develop/serve/main.py);
执行[client.py](https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/client/client.py)进行访问时，出现
![image](https://user-images.githubusercontent.com/13477849/47707304-7905d380-dc66-11e8-9796-e64945d99006.png)
通过gdb解析core文件，得到：
![image](https://user-images.githubusercontent.com/13477849/47707484-e9145980-dc66-11e8-901c-a8f06d6d78b8.png)

**Comment by dzhwinter** [comment]
模型可能需要自己save，下载的版本是v2的

**Comment by LiuZheng-Z** [comment]
我是通过基于docker运行的，在自己的测试机上是可以正常运行的。但是在另外的机器上就不行了。模型应该是没有问题的。

**Comment by Superjomn** [comment]
编译的demo是在支持 AVX 指令集的机器上。

你出core是因为那台机器不支持AVX，CPU比较旧

**Comment by LiuZheng-Z** [comment]
@Superjomn 您好，我看这台机器是有avx指令集的，但没有avx2：
![image](https://user-images.githubusercontent.com/13477849/47774055-eda04700-dd26-11e8-8734-06334c049a94.png)
所以想请问是需要在支持avx2指令集的机器上运行才可以吗？
