### ISSUE TITLE
修改book文档开头话术

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/book#641]
由于book开头话术容易引起误解，而且fluid-book并没有视频课程，因此建议对每篇book文档有如下修改：

**以book01为例**

“本教程源代码目录在book/fit_a_line， 初次使用请参考PaddlePaddle安装教程，更多内容请参考本教程的视频课堂”
===>
中文版：
“本教程源代码目录在[book/fit_a_line](https://github.com/PaddlePaddle/book/tree/develop/01.fit_a_line)， 初次使用请您参考[Book文档使用说明](https://github.com/PaddlePaddle/book/blob/develop/README.cn.md#%E8%BF%90%E8%A1%8C%E8%BF%99%E6%9C%AC%E4%B9%A6)。
英文版：
The source code for this tutorial lives on [book/fit_a_line](https://github.com/PaddlePaddle/book/tree/develop/01.fit_a_line). For instructions on getting started with this book, see [Running This Book](https://github.com/PaddlePaddle/book#running-the-book).

**Comment by shanyi15** [comment]
@tink2123 Please check

**Comment by tink2123** [comment]
> 
> 
> @tink2123 Please check

没有意见~赞！

**Comment by shanyi15** [comment]
fixed, thanks
