### ISSUE TITLE
gpu版本docker.paddlepaddlehub.com/book，运行程序会出现core文件

### ISSUE THREAD

**Issue by zhuziying** [PaddlePaddle/book#645]

**Comment by xuezhong** [comment]
您好，麻烦提供下具体信息，包括运行的环境，GPU型号，出core的代码路径，core的打印信息，方便我们定位问题，谢谢~

**Comment by zhuziying** [comment]
在 2018-12-03 11:29:10，"xuezhong" <notifications@github.com> 写道：


您好，麻烦提供下具体信息，包括运行的环境，GPU型号，出core的代码路径，core的打印信息，方便我们定位问题，谢谢~

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

运行环境是k8s+docker，GPU型号是GeForce GTX 1060，使用的镜像是docker.paddlepaddlehub.com/book:latest-gpu，运行的第一个实验fit_a_line中的train.py，尝试了两个版本（paddle.v2、paddle.fluid）都会生成core.x文件，镜像里面没有调试工具，我安装了gdb，但是调试信息中重要的地方是问号，不知道是什么错误。

**Comment by xuezhong** [comment]
复现命令是什么？方便的可以截图看下

**Comment by xuezhong** [comment]
https://github.com/PaddlePaddle/Paddle/issues/14684 在这个issue中有对这个问题的详细讨论，此问题close了
