### ISSUE TITLE
book/03.image_classification/ GPU第一次正常第二次运行报错

### ISSUE THREAD

**Issue by zhuziying** [PaddlePaddle/book#661]
Pass 0, Batch 0, Cost 3.194520, Acc 0.078125
...................................................................................................
Pass 100, Batch 0, Cost 1.607098, Acc 0.445312
...................................................................................................
Pass 200, Batch 0, Cost 1.341645, Acc 0.500000
...................................................................................................
Pass 300, Batch 0, Cost 1.294024, Acc 0.546875
..........................................................................................

EnforceNotMetTraceback (most recent call last)
<ipython-input-2-4cf485e0cb2e> in <module>()
    207     # For demo purpose, the training runs on CPU
    208     # Please change accordingly.
--> 209     main(use_cuda=True)

<ipython-input-2-4cf485e0cb2e> in main(use_cuda)
    199     save_path = "image_classification_resnet.inference.model"
    200 
--> 201     train(use_cuda=use_cuda, params_dirname=save_path)
    202 
    203     infer(use_cuda=use_cuda, params_dirname=save_path)

<ipython-input-2-4cf485e0cb2e> in train(use_cuda, params_dirname)
    127                                               [predict], exe)
    128 
--> 129     train_loop()
    130 
    131 

<ipython-input-2-4cf485e0cb2e> in train_loop()
    119 
    120             avg_cost_test, accuracy_test = train_test(
--> 121                 test_program, reader=test_reader)
    122             print('\nTest with Pass {0}, Loss {1:2.2}, Acc {2:2.2}'.format(
    123                 pass_id, avg_cost_test, accuracy_test))

<ipython-input-2-4cf485e0cb2e> in train_test(program, reader)
     88                 program=program,
     89                 feed=feeder_test.feed(test_data),
---> 90                 fetch_list=[avg_cost, acc])
     91             accumulated = [
     92                 x[0] + x[1][0] for x in zip(accumulated, avg_cost_np)

/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.pyc in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    468 
    469         self._feed_data(program, feed, feed_var_name, scope)
--> 470         self.executor.run(program.desc, scope, 0, True, True)
    471         outs = self._fetch_data(fetch_list, fetch_var_name, scope)
    472         if return_numpy:

EnforceNotMet: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks: 
0       0x7f2451449a12p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7f2452ac9906p paddle::framework::Tensor::check_memory_size() const + 214
2       0x7f2451452b69p float const* paddle::framework::Tensor::data<float>() const + 25
3       0x7f2451b3ddcap paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1738
4       0x7f2451b3ef30p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 32
5       0x7f2452a5585ap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 506
6       0x7f2452a51d3fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 447
7       0x7f245150f957p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 247
8       0x7f2451510635p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 117
9       0x7f245142e75ap
10      0x7f245145f212p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2338
11            0x4c5326p PyEval_EvalFrameEx + 37958
12            0x4b9b66p PyEval_EvalCodeEx + 774
13            0x4c17c6p PyEval_EvalFrameEx + 22758
14            0x4b9b66p PyEval_EvalCodeEx + 774
15            0x4c1f56p PyEval_EvalFrameEx + 24694
16            0x4b9b66p PyEval_EvalCodeEx + 774
17            0x4c1f56p PyEval_EvalFrameEx + 24694
18            0x4b9b66p PyEval_EvalCodeEx + 774
19            0x4c1f56p PyEval_EvalFrameEx + 24694
20            0x4b9b66p PyEval_EvalCodeEx + 774
21            0x4c1f56p PyEval_EvalFrameEx + 24694
22            0x4b9b66p PyEval_EvalCodeEx + 774
23            0x4bf7a2p PyEval_EvalFrameEx + 14530
24            0x4b9b66p PyEval_EvalCodeEx + 774
25            0x4c17c6p PyEval_EvalFrameEx + 22758
26            0x4b9b66p PyEval_EvalCodeEx + 774
27            0x4c17c6p PyEval_EvalFrameEx + 22758
28            0x4b9b66p PyEval_EvalCodeEx + 774
29            0x4d57a3p
30            0x4a587ep PyObject_Call + 62
31            0x4be51ep PyEval_EvalFrameEx + 9790
32            0x4b9b66p PyEval_EvalCodeEx + 774
33            0x4c1f56p PyEval_EvalFrameEx + 24694
34            0x4b9b66p PyEval_EvalCodeEx + 774
35            0x4c17c6p PyEval_EvalFrameEx + 22758
36            0x4b9b66p PyEval_EvalCodeEx + 774
37            0x4c1f56p PyEval_EvalFrameEx + 24694
38            0x4b9b66p PyEval_EvalCodeEx + 774
39            0x4c1f56p PyEval_EvalFrameEx + 24694
40            0x4b9b66p PyEval_EvalCodeEx + 774
41            0x4d57a3p
42            0x4a587ep PyObject_Call + 62
43            0x4be51ep PyEval_EvalFrameEx + 9790
44            0x4b9b66p PyEval_EvalCodeEx + 774
45            0x4d57a3p
46            0x4a587ep PyObject_Call + 62
47            0x4be51ep PyEval_EvalFrameEx + 9790
48            0x4b9b66p PyEval_EvalCodeEx + 774
49            0x4c1f56p PyEval_EvalFrameEx + 24694
50            0x4b9b66p PyEval_EvalCodeEx + 774
51            0x4c1f56p PyEval_EvalFrameEx + 24694
52            0x4b9b66p PyEval_EvalCodeEx + 774
53            0x4d57a3p
54            0x4a587ep PyObject_Call + 62
55            0x4be51ep PyEval_EvalFrameEx + 9790
56            0x4b9b66p PyEval_EvalCodeEx + 774
57            0x4c1f56p PyEval_EvalFrameEx + 24694
58            0x4b9b66p PyEval_EvalCodeEx + 774
59            0x4c1f56p PyEval_EvalFrameEx + 24694
60            0x4b9b66p PyEval_EvalCodeEx + 774
61            0x4c1f56p PyEval_EvalFrameEx + 24694
62            0x4b9b66p PyEval_EvalCodeEx + 774
63            0x4c17c6p PyEval_EvalFrameEx + 22758
64            0x4b9b66p PyEval_EvalCodeEx + 774
65            0x4bf7a2p PyEval_EvalFrameEx + 14530
66            0x4b9b66p PyEval_EvalCodeEx + 774
67            0x4c17c6p PyEval_EvalFrameEx + 22758
68            0x4b9b66p PyEval_EvalCodeEx + 774
69            0x4d5669p
70            0x4a587ep PyObject_Call + 62
71            0x51a866p
72            0x4939ccp Py_Main + 1612
73      0x7f249ccc1830p __libc_start_main + 240
74            0x493299p _start + 41

**Comment by junjun315** [comment]
看样子像是运行时资源不太够了。试着在docker运行的时候docker stats 看看使用情况。然后调整一下允许docker使用的内存

**Comment by shippingwang** [comment]
@zhuziying 
![image](https://user-images.githubusercontent.com/13645332/50151133-f5c63d00-02fa-11e9-9214-88d69685978e.png)
没有复现问题

**Comment by zhuziying** [comment]
@shippingwang 我使用的是jupyter运行的，我会试一下直接在镜像里面运行。

**Comment by zhuziying** [comment]
@junjun315 好的 我会试一下

**Comment by zhuziying** [comment]
@shippingwang 如你所说的，运行没有问题，3Q。可能是jupyter的问题，每次运行结束后，也会有一个线程占用，所以导致的问题。
