### ISSUE TITLE
快速入门-识别数字出现问题

### ISSUE THREAD

**Issue by mingkai1369** [PaddlePaddle/book#674]
线性回归通过，不通的是识别数字，网址：http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/quick_start/fit_a_line/README.cn.html
![image](https://user-images.githubusercontent.com/37862032/52769942-ccacf900-306c-11e9-8f32-fe1c0b8b9d1e.png)

**Comment by mingkai1369** [comment]
![image](https://user-images.githubusercontent.com/37862032/52770217-74c2c200-306d-11e9-853d-e18b6f49cee7.png)

**Comment by heavengate** [comment]
当时没实现这个功能,  1.3有fix
