### ISSUE TITLE
最新版09.gan报错 NameError: name 'run_ce' is not defined

### ISSUE THREAD

**Issue by fionwang223** [PaddlePaddle/book#699]
运行环境：
百度云paddle cloud产品，Python3，gpu

问题：
NameError: name 'run_ce' is not defined

报错截图：
![捕获4](https://user-images.githubusercontent.com/9932424/56404507-b5bb9a80-6299-11e9-85bf-e50a794d6a2d.PNG)

**Comment by fionwang223** [comment]
这个问题我自己已经找到了，README.cn.md文档中超参数代码块中没有定义run_ce的值。
我想问下**run_ce**这参数指的是是否使用model ce，**model_ce**指的是什么？

**Comment by junjun315** [comment]
model_ce是我们内部使用的一个标记，用作测试跟踪的。在另外的repo：paddle/models 的代码里比较常见。
