### ISSUE TITLE
最新版09.gan报错 output_dcgan/{:04d}_{:04d}.png不存在

### ISSUE THREAD

**Issue by fionwang223** [PaddlePaddle/book#700]
运行环境：
百度云paddle cloud产品，Python3，gpu

问题：
FileNotFoundError: [Errno 2] No such file or directory: 'output_dcgan/0010_0460.png'

报错截图：
![捕获7](https://user-images.githubusercontent.com/9932424/56410436-b3643b00-62af-11e9-882a-39fdd4fc165e.PNG)

**Comment by fionwang223** [comment]
这个问题我自己解决了，把run_ce的值改为False就能够得到output_dcgan路径及其路径下输出的图片。

**Comment by junjun315** [comment]
谢谢反馈。run_ce是我们研发环境的选项，之后将从代码里挪除它。
