### ISSUE TITLE
02.recognize_digits 中 print中step和epoch_id顺序似乎反了

### ISSUE THREAD

**Issue by Steffy-zxf** [PaddlePaddle/book#709]
train.py中第128行打印的step和epoch_id顺序似乎反了，一个batch应该是一个step，一个pass应该是一个epoch。
![image](https://user-images.githubusercontent.com/48793257/57205216-9342b480-6fef-11e9-8c09-2769d0d4bf72.png)
若是按照上图顺序打印，则打印结果奇怪，batch一直为0。
![image](https://user-images.githubusercontent.com/48793257/57205226-ab1a3880-6fef-11e9-932d-b21f915bad77.png)

**Comment by tink2123** [comment]
感谢反馈，文档中对Pass 和 Batch 的解释如下图所示，和普遍理解不一致，可能造成了困惑，我们修改一下
![image](https://user-images.githubusercontent.com/31891223/59739996-4b26db00-9299-11e9-9c32-78c33769cd20.png)
