### ISSUE TITLE
book 01-fit_a_line模型文档链接失效

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/book#712]
如图所示，该模型文档中很多链接失效, 若蓝色文字不是链接，建议将字体修改为黑色。
<img width="577" alt="01" src="https://user-images.githubusercontent.com/37854899/57594236-a286ac80-7571-11e9-9943-877db73323d4.png">
<img width="919" alt="02" src="https://user-images.githubusercontent.com/37854899/57594249-ad414180-7571-11e9-9039-7a0cc64bbdcc.png">
<img width="535" alt="03" src="https://user-images.githubusercontent.com/37854899/57594259-b500e600-7571-11e9-8cd5-36e5c1793f10.png">
<img width="443" alt="04" src="https://user-images.githubusercontent.com/37854899/57594266-be8a4e00-7571-11e9-9cd1-d89ad98b523c.png">
<img width="402" alt="05" src="https://user-images.githubusercontent.com/37854899/57594272-c2b66b80-7571-11e9-9ea8-43cf1855c355.png">

**Comment by ceci3** [comment]
你好，链接都是维基百科的，所以这个链接暂时连接不上
