### ISSUE TITLE
typo in BuildStrategy section

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/book#714]
link:
http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/fluid_cn.html#sync_batch_norm
"不支持FP16培训" should be "不支持FP16训练".

**Comment by AIpioneer** [comment]
好的，谢谢反馈@shanyi15

**Comment by xsrobin** [comment]
多谢反馈，我们会在下个版本解决这个问题。希望您能给我们的文档提更多的宝贵意见。
