### ISSUE TITLE
01.fit_a_line中输出图像后报错

### ISSUE THREAD

**Issue by luckeriam** [PaddlePaddle/book#743]
在输出图像的时候提示：

/opt/conda/envs/python-3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

**Comment by ceci3** [comment]
你好，请问这个Warning有影响到什么吗？代码里的matplotlib.use()是在import matplotlib.pyplot之前调用的，符合warning里的 matplotlib.use() must be called before pylab, matplotlib.pyplot 这个要求

**Comment by ceci3** [comment]
跟用户沟通，这个Warning 不影响正常运行
