### ISSUE TITLE
请问推荐系统的官方例子的训练速度是怎么样的

### ISSUE THREAD

**Issue by lijc210** [PaddlePaddle/book#763]
我这边用的是单卡Tesla V100-SXM2，3天存训练了不到2000轮，loss 2.4

**Comment by hutuxian** [comment]
您好，感谢使用PaddlePaddle。
我们使用单卡Tesla V100-SXM2也测试了一下，训练一个epoch平均68s，测试一次大约7.86s。供您参考。
