### ISSUE TITLE
book/image_classification的demo中，执行sh train.sh报错：Unknown class type: cudnn_conv

### ISSUE THREAD

**Issue by yehanzheng** [PaddlePaddle/book#77]
I0222 07:10:44.978152   120 Trainer.cpp:170] trainer mode: Normal
F0222 07:10:44.979224   120 ClassRegistrar.h:66] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: cudnn_conv
*** Check failure stack trace: ***
    @     0x7fe16de95daa  (unknown)
    @     0x7fe16de95ce4  (unknown)
    @     0x7fe16de956e6  (unknown)
    @     0x7fe16de98687  (unknown)
    @           0x600835  paddle::Layer::create()
    @           0x538940  _ZZN6paddle13NeuralNetwork4initERKNS_11ModelConfigESt8functionIFviPNS_9ParameterEEERKSt6vectorINS_19enumeration_wrapper13ParameterTypeESaISB_EEbENKUlRKNS_11LayerConfigEE_clESI_
    @           0x539d5b  paddle::NeuralNetwork::init()
    @           0x5479d2  paddle::MultiGradientMachine::MultiGradientMachine()
    @           0x53efde  paddle::GradientMachine::create()
    @           0x67bc98  paddle::TrainerInternal::init()
    @           0x6783ee  paddle::Trainer::init()
    @           0x5132a9  main
    @     0x7fe16d0a1f45  (unknown)
    @           0x51f2a5  (unknown)
    @              (nil)  (unknown)
n_in != n_out
n_in != n_out
/usr/local/bin/paddle: line 109:   120 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by qingqing01** [comment]
脚本默认[使用GPU训练](https://github.com/PaddlePaddle/book/blob/develop/image_classification/train.sh#L24)，是不是您使用的CPU版本？

**Comment by yehanzheng** [comment]
我使用的是cpu-demo-latest版本

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/book/blob/develop/image_classification/train.sh#L24  这行改成 --use_gpu=false 即可。

**Comment by yehanzheng** [comment]
确实是，抱歉
但我改为--use_gpu=false之后，运行train.sh出现以下错误
I0222 07:22:00.873217   143 Trainer.cpp:170] trainer mode: Normal
I0222 07:22:01.370261   143 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
F0222 07:22:01.379647   143 Util.cpp:298] Check failed: is Fail to open data/train.list

我使用docker的安装方式

**Comment by qingqing01** [comment]
```data/train.list``` 文件是否存在？ 下载数据了嘛？

**Comment by yehanzheng** [comment]
知道原因了，因为demo文档里是说执行./data/get_data.sh，所以下载的数据都放到和data同级目录了，而不是data内，我把下载的文件都放进data/下面即可。但是又出现新的问题：
I0222 07:40:40.505312   297 Trainer.cpp:170] trainer mode: Normal
I0222 07:40:40.714889   297 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0222 07:40:40.732405   297 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0222 07:40:40.738922   297 GradientMachine.cpp:134] Initing parameters..
I0222 07:40:41.532263   297 GradientMachine.cpp:141] Init parameters done.
F0222 07:40:41.827276   302 PythonUtil.h:345] Check failed: (data) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/home/book/image_classification', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
Python Error: <type 'exceptions.IndexError'> : too many indices
Python Callstack:
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/PyDataProvider2.py : 132
            /home/book/image_classification/dataprovider.py : 41
Calling iterator next error
*** Check failure stack trace: ***
    @     0x7f9a9488edaa  (unknown)
    @     0x7f9a9488ece4  (unknown)
    @     0x7f9a9488e6e6  (unknown)
    @     0x7f9a94891687  (unknown)
    @           0x56e42c  paddle::PyDataProvider2::loadThread()
    @     0x7f9a9440ba60  (unknown)
    @     0x7f9a956a1184  start_thread
    @     0x7f9a93b7337d  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:   297 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by qingqing01** [comment]
>  /home/book/image_classification/dataprovider.py : 41

这行是啥？ 更新代码呢?

**Comment by yehanzheng** [comment]
更新代码后这个错误消失了，但出现了新错误，应该是开始训练了，但是执行几次随机seed之后，就会被killed掉，resnet和vgg都有这个问题：
[INFO 2017-02-22 07:49:37,121 networks.py:1466] The input order is [image, label]
[INFO 2017-02-22 07:49:37,122 networks.py:1472] The output order is [__cost_0__]
I0222 07:49:37.133262   426 Trainer.cpp:170] trainer mode: Normal
I0222 07:49:37.347053   426 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0222 07:49:37.369861   426 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0222 07:49:37.381635   426 GradientMachine.cpp:134] Initing parameters..
I0222 07:49:38.203049   426 GradientMachine.cpp:141] Init parameters done.
I0222 07:49:42.664607   432 ThreadLocal.cpp:37] thread use undeterministic rand seed:433
I0222 07:49:43.363451   427 ThreadLocal.cpp:37] thread use undeterministic rand seed:428
I0222 07:49:43.418203   430 ThreadLocal.cpp:37] thread use undeterministic rand seed:431
I0222 07:49:43.427688   429 ThreadLocal.cpp:37] thread use undeterministic rand seed:430
I0222 07:49:43.502692   428 ThreadLocal.cpp:37] thread use undeterministic rand seed:429
/usr/local/bin/paddle: line 109:   426 Killed                  ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by qingqing01** [comment]
数据总共也不大，全部缓存内存应该不会爆吧，可否看下内存是否有增长？(top命令可以~)
```
du -h data/cifar-10-batches-py/
178M	data/cifar-10-batches-py/
```
下面是我运行的log

```
I0222 15:57:46.451283 19703 Util.cpp:160] commandline: /home/xxx/opt/paddle/bin/paddle_trainer --config=models/vgg.py --use_gpu=0 --trainer_count=4 --log_period=10 --num_passes=300 --save_dir=output
[INFO 2017-02-22 15:57:46,740 layers.py:2010] output for __conv_0__: c = 64, h = 32, w = 32, size = 65536
[INFO 2017-02-22 15:57:46,743 layers.py:2010] output for __conv_1__: c = 64, h = 32, w = 32, size = 65536
[INFO 2017-02-22 15:57:46,746 layers.py:2119] output for __pool_0__: c = 64, h = 16, w = 16, size = 16384
[INFO 2017-02-22 15:57:46,747 layers.py:2010] output for __conv_2__: c = 128, h = 16, w = 16, size = 32768
[INFO 2017-02-22 15:57:46,750 layers.py:2010] output for __conv_3__: c = 128, h = 16, w = 16, size = 32768
[INFO 2017-02-22 15:57:46,752 layers.py:2119] output for __pool_1__: c = 128, h = 8, w = 8, size = 8192
[INFO 2017-02-22 15:57:46,754 layers.py:2010] output for __conv_4__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-02-22 15:57:46,757 layers.py:2010] output for __conv_5__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-02-22 15:57:46,760 layers.py:2010] output for __conv_6__: c = 256, h = 8, w = 8, size = 16384
[INFO 2017-02-22 15:57:46,762 layers.py:2119] output for __pool_2__: c = 256, h = 4, w = 4, size = 4096
[INFO 2017-02-22 15:57:46,764 layers.py:2010] output for __conv_7__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-02-22 15:57:46,766 layers.py:2010] output for __conv_8__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-02-22 15:57:46,769 layers.py:2010] output for __conv_9__: c = 512, h = 4, w = 4, size = 8192
[INFO 2017-02-22 15:57:46,772 layers.py:2119] output for __pool_3__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-02-22 15:57:46,773 layers.py:2010] output for __conv_10__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-02-22 15:57:46,776 layers.py:2010] output for __conv_11__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-02-22 15:57:46,778 layers.py:2010] output for __conv_12__: c = 512, h = 2, w = 2, size = 2048
[INFO 2017-02-22 15:57:46,781 layers.py:2119] output for __pool_4__: c = 512, h = 1, w = 1, size = 512
[INFO 2017-02-22 15:57:46,786 networks.py:1472] The input order is [image, label]
[INFO 2017-02-22 15:57:46,787 networks.py:1478] The output order is [__cost_0__]
I0222 15:57:46.802176 19703 Trainer.cpp:165] trainer mode: Normal
I0222 15:57:47.076678 19703 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
I0222 15:57:47.078114 19703 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
I0222 15:57:47.078555 19703 GradientMachine.cpp:86] Initing parameters..
I0222 15:57:48.014125 19703 GradientMachine.cpp:93] Init parameters done.
.........
I0222 16:03:39.856623 19703 TrainerInternal.cpp:165]  Batch=10 samples=1280 AvgCost=2.41825 CurrentCost=2.41825 Eval: classification_error_evaluator=0.888281  CurrentEval: classification_error_evaluator=0.888281
```

**Comment by yehanzheng** [comment]
我将docker的内存从2G调整到4G，可以解决这个问题，感谢paddle团队的快速响应！

**Comment by qingqing01** [comment]
@yehanzheng  另外 https://github.com/PaddlePaddle/book/pull/78 稍微改了下dataprovider，这个issue就close了。

谢谢！

**Comment by yehanzheng** [comment]
good job!
