### ISSUE TITLE
内容修改申请：book/02.recognize_digits/README.cn.md 

### ISSUE THREAD

**Issue by baihaojie2011** [PaddlePaddle/book#774]
您好，我在做 paddle 教学过程中发现手写字体识别的代码，在教学的时候还有可以修改的空间，因为有些代码冗余，没办法给学员解释，所以申请对代码做一些修改。

### 1.请删除代码：  
删除函数：optimizer_program
![image](https://user-images.githubusercontent.com/27996442/61215266-f0b85780-a73c-11e9-87b9-18e058d0f10f.png)
该代码并没有在后续代码中调用，写了却没有使用，对学员没法解释

### 2.修改代码：  
![image](https://user-images.githubusercontent.com/27996442/61215396-599fcf80-a73d-11e9-8f6d-1204c95c7b22.png)
是否可以考虑修改为：
```python
删除：# 输入的原始图像数据，大小为28*28*1
删除：img = fluid.layers.data(name='img', shape=[1, 28, 28], dtype='float32')
删除：# 标签层，名称为label,对应输入图片的类别标签
删除：label = fluid.layers.data(name='label', shape=[1], dtype='int64')
# 告知网络传入的数据分为两部分，第一部分是img值，第二部分是label值
修改：feeder = fluid.DataFeeder(feed_list=[‘img‘, ’label‘’], place=place)
```
由于 变量和数据层已经在前面函数定义过了，这里又定义一遍，不太好解释

### 3.增加一点注释：
![image](https://user-images.githubusercontent.com/27996442/61215677-1c880d00-a73e-11e9-916c-848a99a50e84.png)
绝大多数学员应该是对 Image 的操作是不熟悉的，所以如果能加上注释可能更方便学员学习

**Comment by zhhsplendid** [comment]
感谢您的反馈！我转发我们这边负责这块book的人，审核一下然后修改
