### ISSUE TITLE
Network structure not consistent with proposed DCGAN

### ISSUE THREAD

**Issue by a411919924** [PaddlePaddle/book#851]
The original DCGAN proposed to replace all fully connected layers with convolutional layers. But in the DCGAN implementation in PaddlePaddle, the developer used a fully connected layer as the last layer in both the generator and discriminator. This may raise an inconsistent result.

**Comment by ceci3** [comment]
Thanks for your attention. It is inconsistent with origin paper.  DCGAN in PaddlePaddle developed based on https://github.com/carpedm20/DCGAN-tensorflow,  it uses linear in the network, and the result seems not bad than origin paper, so I guess fully-connected layer or convolution layer is not that important for the last layer.

**Comment by a411919924** [comment]
Thanks for the quick response and good explanation.
