### ISSUE TITLE
06情感分析代码出现维度错误

### ISSUE THREAD

**Issue by Er1-x** [PaddlePaddle/book#853]
错误提示如下，使用的是CNN模型
/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "cnn.py", line 203, in <module>
    main(use_cuda)
  File "cnn.py", line 197, in main
    infer(use_cuda, params_dirname)
  File "cnn.py", line 178, in infer
    fetch_list=fetch_targets)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 902, in _run_program
    self._feed_data(program, feed, feed_var_name, scope)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 580, in _feed_data
    check_feed_shape_type(var, cur_feed)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 230, in check_feed_shape_type
    (var.name, len(var.shape), var.shape, feed_shape))
ValueError: The fed Variable u'words' should have dimensions = 1, shape = (-1L,), but received fed shape [-1, 1L] on each device
aistudio@jupyter-284539-468867:~/work$

**Comment by Aurelius84** [comment]
请问下，使用的训练代码是什么时候的版本？
从报错来看，是输入words的shape不匹配，可能尝试如下方法：

1. 定义`words`的`fluid.data`输入为[-1]，但实际训练输入的shape为[-1, 1]，可以尝试对输入的words调用`fluid.layers.squeeze(words, -1)`移除最后多余的shape.

**Comment by Er1-x** [comment]
用的就是这个paddlepaddle/book中的版本

**Comment by Er1-x** [comment]
def infer(use_cuda, params_dirname=None):
    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    word_dict = paddle.dataset.imdb.word_dict()

    exe = fluid.Executor(place)

    inference_scope = fluid.core.Scope()
    with fluid.scope_guard(inference_scope):
        # Use fluid.io.load_inference_model to obtain the inference program desc,
        # the feed_target_names (the names of variables that will be feeded
        # data using feed operators), and the fetch_targets (variables that
        # we want to obtain data from using fetch operators).
        [inferencer, feed_target_names,
         fetch_targets] = fluid.io.load_inference_model(params_dirname, exe)

        # Setup input by creating LoDTensor to represent sequence of words.
        # Here each word is the basic element of the LoDTensor and the shape of
        # each word (base_shape) should be [1] since it is simply an index to
        # look up for the corresponding word vector.
        # Suppose the length_based level of detail (lod) info is set to [[3, 4, 2]],
        # which has only one lod level. Then the created LoDTensor will have only
        # one higher level structure (sequence of words, or sentence) than the basic
        # element (word). Hence the LoDTensor will hold data for three sentences of
        # length 3, 4 and 2, respectively.
        # Note that lod info should be a list of lists.
        reviews_str = [
            'read the book forget the movie', 'this is a great movie',
            'this is very bad'
        ]
        reviews = [c.split() for c in reviews_str]

        UNK = word_dict['<unk>']
        lod = []
        for c in reviews:
            lod.append([np.int64(word_dict.get(words, UNK)) for words in c])

        base_shape = [[len(c) for c in lod]]

        tensor_words = fluid.create_lod_tensor(lod, base_shape, place)
        assert feed_target_names[0] == "words"
        results = exe.run(
            inferencer,
            feed={feed_target_names[0]: tensor_words},
            fetch_list=fetch_targets,
            return_numpy=False)
        np_data = np.array(results[0])
        for i, r in enumerate(np_data):
            print("Predict probability of ", r[0], " to be positive and ", r[1],
                  " to be negative for review \'", reviews_str[i], "\'")
这是出现问题的函数，问题出现在 results = exe.run()中

**Comment by lfchener** [comment]
book 后续可能不会再维护了
最新源码可以参考：
https://github.com/PaddlePaddle/FluidDoc/tree/release/1.8/doc/fluid/user_guides/nlp_case/understand_sentiment#application-model

**Comment by Er1-x** [comment]
谢谢，新版本代码可以正常运行，

**Comment by Aurelius84** [comment]
> 谢谢，新版本代码可以正常运行，

@Er11c 请问是否已经解决了您的问题？如果问题已解决，辛苦close下哈~~
