### ISSUE TITLE
语义序列标注修改输入出现的问题

### ISSUE THREAD

**Issue by Gs-Zhang** [PaddlePaddle/book#855]
在学习 语义序列标注 官方案例时
利用那个构造了 ipynb文件。
在没有进行修改前完美运行。
尝试修改数据结构，即把emb_layer修改成【word，verb】层，而不是之前的8层
并且对数据读取后也进行了处理，处理为【word,verb】的形式，出现了一系列错误
现在把ipynb文件放进来，请大佬们看一下是哪里的问题？
[label_semantic_roles.zip](https://github.com/PaddlePaddle/book/files/4686424/label_semantic_roles.zip)

**Comment by Gs-Zhang** [comment]
重启解释器后，出现了
AttributeError                            Traceback (most recent call last)
 in 
      3 
      4 
----> 5 embedding_parm = fluid.global_scope().find_var(emb_layers.name).get_tensor()
      6 embedding_parm.set(load_parameter(con1105.get_embedding(),word_dict_len,word_dim),place)
      7 

AttributeError: 'list' object has no attribute 'name'



[-]

**Comment by gongweibao** [comment]
emb_layers.name ？
