### ISSUE TITLE
[V2.SimpleCode]第三章，图像分类 image_classification

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#86]
[V2.SimpleCode]第三章，图像分类 image_classification

**Comment by zhuanxuhit** [comment]
看了之前 https://github.com/PaddlePaddle/book/tree/develop/image_classification 的文章，作为一个小白用户，太专业了，里面就是介绍了各种模型，然后最后给了个代码，太专业。看不懂，看到一篇用TensorFlow讲解的CNN就很好，https://github.com/llSourcell/How_to_make_a_tensorflow_image_classifier_LIVE/blob/master/demonotes.ipynb，感觉可以基于这个用paddle实现下

**Comment by llxxxll** [comment]
@zhuanxuhit v2.simplecode 会比TF更简单

**Comment by gangliao** [comment]
测试新api

遇到问题：

0. 目前新增的python code并没有把打包信息编译进去，导致编译出来的python包，还不包含新增内容。
1. 新的dataset下载数据好像没有输出信息。。。。

PR in https://github.com/PaddlePaddle/Paddle/pull/1485/files
